version: "3.8"

services:
  api-service:
    build: ./api-service
    ports:
      - "8001:8000"
    depends_on:
      - ml-service

  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"
