version: "3.9"

services:
  ml-service:
    build: ./ml-service
    container_name: ml-service
    ports:
      - "8001:8001"
    volumes:
      - ./ml-service/trained_models:/app/trained_models
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload

  api-service:
    build: ./api-service
    container_name: api-service
    ports:
      - "8000:8000"
    depends_on:
      - ml-service
    environment:
      ML_SERVICE_URL: "http://ml-service:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
